In [1]:
import pandas as pd, os

In [9]:
!dir ../donnees/meteo/2023

synop.202301.csv  synop.202304.csv  synop.202307.csv  synop.202310.csv
synop.202302.csv  synop.202305.csv  synop.202308.csv
synop.202303.csv  synop.202306.csv  synop.202309.csv

In [10]:
repertoire='../donnees/meteo/2023'
filename = 'synop.202301.csv'
meteo = pd.read_csv(os.path.join(repertoire, filename),
                   sep=';',
                   usecols=['numer_sta','date','dd','ff','t','u','vv',
                            'pres','rr1','rr3','rr6','rr12','rr24'],
                   na_values='mq',
                   dtype={'numer_sta':str,'date':str},
                  ).rename( columns={'numer_sta':'Station',
                                      'date':'DateHeure',
                                      'dd':'DirectionVent',
                                      'ff':'VitesseVent',
                                      't':'Temperature',
                                      'u':'Humidite',
                                      'vv':'Visibilite',
                                      'pres':'Pression',
                                      'rr1' :'Precipitation01',
                                      'rr3' :'Precipitation03',
                                      'rr6' :'Precipitation06',
                                      'rr12':'Precipitation12',
                                      'rr24':'Precipitation24'})
meteo.reset_index().drop(columns='index',inplace=True)
meteo["DateHeure"] = pd.to_datetime(meteo["DateHeure"], format='%Y%m%d%H%M%S')
meteo.Temperature  = meteo.Temperature - 273.15
meteo.Pression     = meteo.Pression / 100
meteo.Visibilite   = meteo.Visibilite / 1000
meteo['Mois']      = meteo.DateHeure.dt.month
meteo['Annee']     = meteo.DateHeure.dt.year
meteo['AnneeMois'] = meteo.DateHeure.dt.year*100 + meteo.DateHeure.dt.month
meteo['Semaine']   = meteo.DateHeure.dt.isocalendar().week
meteo['MoisJour']  = meteo.DateHeure.dt.month*100 + meteo.DateHeure.dt.day
meteo['JourA']     = meteo.DateHeure.dt.dayofyear
meteo.head()

,Station,DateHeure,DirectionVent,VitesseVent,Temperature,Humidite,Visibilite,Pression,Precipitation01,Precipitation03,Precipitation06,Precipitation12,Precipitation24,Mois,Annee,AnneeMois,Semaine,MoisJour,JourA
0,07005,2023-01-01,190.0,3.2,13.4,67.0,20.00,1001.1,-0.1,-0.1,-0.1,-0.1,1.6,1,2023,202301,52,101,1
1,07015,2023-01-01,200.0,8.6,14.0,61.0,51.27,1004.1,-0.1,-0.1,-0.1,-0.1,4.5,1,2023,202301,52,101,1
2,07020,2023-01-01,230.0,12.0,11.8,83.0,6.00,1006.5,-0.1,3.6,5.4,5.6,22.0,1,2023,202301,52,101,1
3,07027,2023-01-01,220.0,11.5,14.4,74.0,53.37,1001.7,0.0,0.2,0.8,0.8,7.0,1,2023,202301,52,101,1
4,07037,2023-01-01,200.0,9.3,13.5,62.0,48.85,992.4,-0.1,-0.1,-0.1,-0.1,1.0,1,2023,202301,52,101,1

In [12]:
d1 = pd.read_csv('../donnees/meteo/2023/synop.202301.csv',sep=';',usecols=['numer_sta','date','dd','ff','t','u','vv',
                                                        'pres','rr1','rr3','rr6','rr12','rr24'])
d2 = pd.read_csv('../donnees/meteo/2023/synop.202302.csv',sep=';',usecols=['numer_sta','date','dd','ff','t','u','vv',
                                                        'pres','rr1','rr3','rr6','rr12','rr24'],)

In [13]:
d3 = pd.concat([d1,d2],axis=0)
d3.head()

,numer_sta,date,dd,ff,t,u,vv,pres,rr1,rr3,rr6,rr12,rr24
0,7005,20230101000000,190,3.200000,286.550000,67,20000,100110,-0.100000,-0.100000,-0.100000,-0.100000,1.600000
1,7015,20230101000000,200,8.600000,287.150000,61,51270,100410,-0.100000,-0.100000,-0.100000,-0.100000,4.500000
2,7020,20230101000000,230,12.000000,284.950000,83,6000,100650,-0.100000,3.600000,5.400000,5.600000,22.000000
3,7027,20230101000000,220,11.500000,287.550000,74,53370,100170,0.000000,0.200000,0.800000,0.800000,7.000000
4,7037,20230101000000,200,9.300000,286.650000,62,48850,99240,-0.100000,-0.100000,-0.100000,-0.100000,1.000000

In [14]:
pd.concat([d1,d2]).tail()

,numer_sta,date,dd,ff,t,u,vv,pres,rr1,rr3,rr6,rr12,rr24
13045,81401,20230228210000,40,0.800000,298.050000,94,mq,101140,0.200000,3.100000,12.900000,14.700000,72.100000
13046,81405,20230228210000,80,1.800000,299.150000,91,45370,101130,0.600000,0.600000,0.600000,18.600000,18.800000
13047,81408,20230228210000,60,1.500000,300.950000,84,mq,101030,0.000000,0.000000,2.600000,4.200000,4.800000
13048,81415,20230228210000,70,2.400000,297.150000,95,mq,mq,3.800000,3.800000,6.000000,6.000000,6.000000
13049,89642,20230228210000,130,21.100000,266.950000,93,3000,97290,mq,mq,mq,mq,mq

In [14]:
for dirname, _, filenames in os.walk('../donnees/meteo'):
    for filename in filenames:
        print(os.path.join(dirname,filename))

../donnees/meteo\1996\synop.199601.csv
../donnees/meteo\1996\synop.199602.csv
../donnees/meteo\1996\synop.199603.csv
../donnees/meteo\1996\synop.199604.csv
../donnees/meteo\1996\synop.199605.csv
../donnees/meteo\1996\synop.199606.csv
../donnees/meteo\1996\synop.199607.csv
../donnees/meteo\1996\synop.199608.csv
../donnees/meteo\1996\synop.199609.csv
../donnees/meteo\1996\synop.199610.csv
../donnees/meteo\1996\synop.199611.csv
../donnees/meteo\1996\synop.199612.csv
../donnees/meteo\1997\synop.199701.csv
../donnees/meteo\1997\synop.199702.csv
../donnees/meteo\1997\synop.199703.csv
../donnees/meteo\1997\synop.199704.csv
../donnees/meteo\1997\synop.199705.csv
../donnees/meteo\1997\synop.199706.csv
../donnees/meteo\1997\synop.199707.csv
../donnees/meteo\1997\synop.199708.csv
../donnees/meteo\1997\synop.199709.csv
../donnees/meteo\1997\synop.199710.csv
../donnees/meteo\1997\synop.199711.csv
../donnees/meteo\1997\synop.199712.csv
../donnees/meteo\1998\synop.199801.csv
../donnees/meteo\1998\synop.199802.csv
../donnees/meteo\1998\synop.199803.csv
../donnees/meteo\1998\synop.199804.csv
../donnees/meteo\1998\synop.199805.csv
../donnees/meteo\1998\synop.199806.csv
../donnees/meteo\1998\synop.199807.csv
../donnees/meteo\1998\synop.199808.csv
../donnees/meteo\1998\synop.199809.csv
../donnees/meteo\1998\synop.199810.csv
../donnees/meteo\1998\synop.199811.csv
../donnees/meteo\1998\synop.199812.csv
../donnees/meteo\1999\synop.199901.csv
../donnees/meteo\1999\synop.199902.csv
../donnees/meteo\1999\synop.199903.csv
../donnees/meteo\1999\synop.199904.csv
../donnees/meteo\1999\synop.199905.csv
../donnees/meteo\1999\synop.199906.csv
../donnees/meteo\1999\synop.199907.csv
../donnees/meteo\1999\synop.199908.csv
../donnees/meteo\1999\synop.199909.csv
../donnees/meteo\1999\synop.199910.csv
../donnees/meteo\1999\synop.199911.csv
../donnees/meteo\1999\synop.199912.csv
../donnees/meteo\2000\synop.200001.csv
../donnees/meteo\2000\synop.200002.csv
../donnees/meteo\2000\synop.200003.csv
../donnees/meteo\2000\synop.200004.csv
../donnees/meteo\2000\synop.200005.csv
../donnees/meteo\2000\synop.200006.csv
../donnees/meteo\2000\synop.200007.csv
../donnees/meteo\2000\synop.200008.csv
../donnees/meteo\2000\synop.200009.csv
../donnees/meteo\2000\synop.200010.csv
../donnees/meteo\2000\synop.200011.csv
../donnees/meteo\2000\synop.200012.csv
../donnees/meteo\2001\synop.200101.csv
../donnees/meteo\2001\synop.200102.csv
../donnees/meteo\2001\synop.200103.csv
../donnees/meteo\2001\synop.200104.csv
../donnees/meteo\2001\synop.200105.csv
../donnees/meteo\2001\synop.200106.csv
../donnees/meteo\2001\synop.200107.csv
../donnees/meteo\2001\synop.200108.csv
../donnees/meteo\2001\synop.200109.csv
../donnees/meteo\2001\synop.200110.csv
../donnees/meteo\2001\synop.200111.csv
../donnees/meteo\2001\synop.200112.csv
../donnees/meteo\2002\synop.200201.csv
../donnees/meteo\2002\synop.200202.csv
../donnees/meteo\2002\synop.200203.csv
../donnees/meteo\2002\synop.200204.csv
../donnees/meteo\2002\synop.200205.csv
../donnees/meteo\2002\synop.200206.csv
../donnees/meteo\2002\synop.200207.csv
../donnees/meteo\2002\synop.200208.csv
../donnees/meteo\2002\synop.200209.csv
../donnees/meteo\2002\synop.200210.csv
../donnees/meteo\2002\synop.200211.csv
../donnees/meteo\2002\synop.200212.csv
../donnees/meteo\2003\synop.200301.csv
../donnees/meteo\2003\synop.200302.csv
../donnees/meteo\2003\synop.200303.csv
../donnees/meteo\2003\synop.200304.csv
../donnees/meteo\2003\synop.200305.csv
../donnees/meteo\2003\synop.200306.csv
../donnees/meteo\2003\synop.200307.csv
../donnees/meteo\2003\synop.200308.csv
../donnees/meteo\2003\synop.200309.csv
../donnees/meteo\2003\synop.200310.csv
../donnees/meteo\2003\synop.200311.csv
../donnees/meteo\2003\synop.200312.csv
../donnees/meteo\2004\synop.200401.csv
../donnees/meteo\2004\synop.200402.csv
../donnees/meteo\2004\synop.200403.csv
../donnees/meteo\2004\synop.200404.csv
../donnees/meteo\2004\synop.200405.csv
../donnees/meteo\2004\synop.200406.csv
../donnees/meteo\2004\synop.200407.csv
../donnees/meteo\2004\synop.200408.csv
../donnees/meteo\2004\synop.200409.csv
../donnees/meteo\2004\synop.200410.csv
../donnees/meteo\2004\synop.200411.csv
../donnees/meteo\2004\synop.200412.csv
../donnees/meteo\2005\synop.200501.csv
../donnees/meteo\2005\synop.200502.csv
../donnees/meteo\2005\synop.200503.csv
../donnees/meteo\2005\synop.200504.csv
../donnees/meteo\2005\synop.200505.csv
../donnees/meteo\2005\synop.200506.csv
../donnees/meteo\2005\synop.200507.csv
../donnees/meteo\2005\synop.200508.csv
../donnees/meteo\2005\synop.200509.csv
../donnees/meteo\2005\synop.200510.csv
../donnees/meteo\2005\synop.200511.csv
../donnees/meteo\2005\synop.200512.csv
../donnees/meteo\2006\synop.200601.csv
../donnees/meteo\2006\synop.200602.csv
../donnees/meteo\2006\synop.200603.csv
../donnees/meteo\2006\synop.200604.csv
../donnees/meteo\2006\synop.200605.csv
../donnees/meteo\2006\synop.200606.csv
../donnees/meteo\2006\synop.200607.csv
../donnees/meteo\2006\synop.200608.csv
../donnees/meteo\2006\synop.200609.csv
../donnees/meteo\2006\synop.200610.csv
../donnees/meteo\2006\synop.200611.csv
../donnees/meteo\2006\synop.200612.csv
../donnees/meteo\2007\synop.200701.csv
../donnees/meteo\2007\synop.200702.csv
../donnees/meteo\2007\synop.200703.csv
../donnees/meteo\2007\synop.200704.csv
../donnees/meteo\2007\synop.200705.csv
../donnees/meteo\2007\synop.200706.csv
../donnees/meteo\2007\synop.200707.csv
../donnees/meteo\2007\synop.200708.csv
../donnees/meteo\2007\synop.200709.csv
../donnees/meteo\2007\synop.200710.csv
../donnees/meteo\2007\synop.200711.csv
../donnees/meteo\2007\synop.200712.csv
../donnees/meteo\2008\synop.200801.csv
../donnees/meteo\2008\synop.200802.csv
../donnees/meteo\2008\synop.200803.csv
../donnees/meteo\2008\synop.200804.csv
../donnees/meteo\2008\synop.200805.csv
../donnees/meteo\2008\synop.200806.csv
../donnees/meteo\2008\synop.200807.csv
../donnees/meteo\2008\synop.200808.csv
../donnees/meteo\2008\synop.200809.csv
../donnees/meteo\2008\synop.200810.csv
../donnees/meteo\2008\synop.200811.csv
../donnees/meteo\2008\synop.200812.csv
../donnees/meteo\2009\synop.200901.csv
../donnees/meteo\2009\synop.200902.csv
../donnees/meteo\2009\synop.200903.csv
../donnees/meteo\2009\synop.200904.csv
../donnees/meteo\2009\synop.200905.csv
../donnees/meteo\2009\synop.200906.csv
../donnees/meteo\2009\synop.200907.csv
../donnees/meteo\2009\synop.200908.csv
../donnees/meteo\2009\synop.200909.csv
../donnees/meteo\2009\synop.200910.csv
../donnees/meteo\2009\synop.200911.csv
../donnees/meteo\2009\synop.200912.csv
../donnees/meteo\2010\synop.201001.csv
../donnees/meteo\2010\synop.201002.csv
../donnees/meteo\2010\synop.201003.csv
../donnees/meteo\2010\synop.201004.csv
../donnees/meteo\2010\synop.201005.csv
../donnees/meteo\2010\synop.201006.csv
../donnees/meteo\2010\synop.201007.csv
../donnees/meteo\2010\synop.201008.csv
../donnees/meteo\2010\synop.201009.csv
../donnees/meteo\2010\synop.201010.csv
../donnees/meteo\2010\synop.201011.csv
../donnees/meteo\2010\synop.201012.csv
../donnees/meteo\2011\synop.201101.csv
../donnees/meteo\2011\synop.201102.csv
../donnees/meteo\2011\synop.201103.csv
../donnees/meteo\2011\synop.201104.csv
../donnees/meteo\2011\synop.201105.csv
../donnees/meteo\2011\synop.201106.csv
../donnees/meteo\2011\synop.201107.csv
../donnees/meteo\2011\synop.201108.csv
../donnees/meteo\2011\synop.201109.csv
../donnees/meteo\2011\synop.201110.csv
../donnees/meteo\2011\synop.201111.csv
../donnees/meteo\2011\synop.201112.csv
../donnees/meteo\2012\synop.201201.csv
../donnees/meteo\2012\synop.201202.csv
../donnees/meteo\2012\synop.201203.csv
../donnees/meteo\2012\synop.201204.csv
../donnees/meteo\2012\synop.201205.csv
../donnees/meteo\2012\synop.201206.csv
../donnees/meteo\2012\synop.201207.csv
../donnees/meteo\2012\synop.201208.csv
../donnees/meteo\2012\synop.201209.csv
../donnees/meteo\2012\synop.201210.csv
../donnees/meteo\2012\synop.201211.csv
../donnees/meteo\2012\synop.201212.csv
../donnees/meteo\2013\synop.201301.csv
../donnees/meteo\2013\synop.201302.csv
../donnees/meteo\2013\synop.201303.csv
../donnees/meteo\2013\synop.201304.csv
../donnees/meteo\2013\synop.201305.csv
../donnees/meteo\2013\synop.201306.csv
../donnees/meteo\2013\synop.201307.csv
../donnees/meteo\2013\synop.201308.csv
../donnees/meteo\2013\synop.201309.csv
../donnees/meteo\2013\synop.201310.csv
../donnees/meteo\2013\synop.201311.csv
../donnees/meteo\2013\synop.201312.csv
../donnees/meteo\2014\synop.201401.csv
../donnees/meteo\2014\synop.201402.csv
../donnees/meteo\2014\synop.201403.csv
../donnees/meteo\2014\synop.201404.csv
../donnees/meteo\2014\synop.201405.csv
../donnees/meteo\2014\synop.201406.csv
../donnees/meteo\2014\synop.201407.csv
../donnees/meteo\2014\synop.201408.csv
../donnees/meteo\2014\synop.201409.csv
../donnees/meteo\2014\synop.201410.csv
../donnees/meteo\2014\synop.201411.csv
../donnees/meteo\2014\synop.201412.csv
../donnees/meteo\2015\synop.201501.csv
../donnees/meteo\2015\synop.201502.csv
../donnees/meteo\2015\synop.201503.csv
../donnees/meteo\2015\synop.201504.csv
../donnees/meteo\2015\synop.201505.csv
../donnees/meteo\2015\synop.201506.csv
../donnees/meteo\2015\synop.201507.csv
../donnees/meteo\2015\synop.201508.csv
../donnees/meteo\2015\synop.201509.csv
../donnees/meteo\2015\synop.201510.csv
../donnees/meteo\2015\synop.201511.csv
../donnees/meteo\2015\synop.201512.csv
../donnees/meteo\2016\synop.201601.csv
../donnees/meteo\2016\synop.201602.csv
../donnees/meteo\2016\synop.201603.csv
../donnees/meteo\2016\synop.201604.csv
../donnees/meteo\2016\synop.201605.csv
../donnees/meteo\2016\synop.201606.csv
../donnees/meteo\2016\synop.201607.csv
../donnees/meteo\2016\synop.201608.csv
../donnees/meteo\2016\synop.201609.csv
../donnees/meteo\2016\synop.201610.csv
../donnees/meteo\2016\synop.201611.csv
../donnees/meteo\2016\synop.201612.csv
../donnees/meteo\2017\synop.201701.csv
../donnees/meteo\2017\synop.201702.csv
../donnees/meteo\2017\synop.201703.csv
../donnees/meteo\2017\synop.201704.csv
../donnees/meteo\2017\synop.201705.csv
../donnees/meteo\2017\synop.201706.csv
../donnees/meteo\2017\synop.201707.csv
../donnees/meteo\2017\synop.201708.csv
../donnees/meteo\2017\synop.201709.csv
../donnees/meteo\2017\synop.201710.csv
../donnees/meteo\2017\synop.201711.csv
../donnees/meteo\2017\synop.201712.csv
../donnees/meteo\2018\synop.201801.csv
../donnees/meteo\2018\synop.201802.csv
../donnees/meteo\2018\synop.201803.csv
../donnees/meteo\2018\synop.201804.csv
../donnees/meteo\2018\synop.201805.csv
../donnees/meteo\2018\synop.201806.csv
../donnees/meteo\2018\synop.201807.csv
../donnees/meteo\2018\synop.201808.csv
../donnees/meteo\2018\synop.201809.csv
../donnees/meteo\2018\synop.201810.csv
../donnees/meteo\2018\synop.201811.csv
../donnees/meteo\2018\synop.201812.csv
../donnees/meteo\2019\synop.201901.csv
../donnees/meteo\2019\synop.201902.csv
../donnees/meteo\2019\synop.201903.csv
../donnees/meteo\2019\synop.201904.csv
../donnees/meteo\2019\synop.201905.csv
../donnees/meteo\2019\synop.201906.csv
../donnees/meteo\2019\synop.201907.csv
../donnees/meteo\2019\synop.201908.csv
../donnees/meteo\2019\synop.201909.csv
../donnees/meteo\2019\synop.201910.csv
../donnees/meteo\2019\synop.201911.csv
../donnees/meteo\2019\synop.201912.csv
../donnees/meteo\2020\synop.202001.csv
../donnees/meteo\2020\synop.202002.csv
../donnees/meteo\2020\synop.202003.csv
../donnees/meteo\2020\synop.202004.csv
../donnees/meteo\2020\synop.202005.csv
../donnees/meteo\2020\synop.202006.csv
../donnees/meteo\2020\synop.202007.csv
../donnees/meteo\2020\synop.202008.csv
../donnees/meteo\2020\synop.202009.csv
../donnees/meteo\2020\synop.202010.csv
../donnees/meteo\2020\synop.202011.csv
../donnees/meteo\2020\synop.202012.csv
../donnees/meteo\2021\synop.202001.csv
../donnees/meteo\2021\synop.202002.csv
../donnees/meteo\2021\synop.202003.csv
../donnees/meteo\2021\synop.202004.csv
../donnees/meteo\2021\synop.202005.csv
../donnees/meteo\2021\synop.202006.csv
../donnees/meteo\2021\synop.202007.csv
../donnees/meteo\2021\synop.202008.csv
../donnees/meteo\2021\synop.202009.csv
../donnees/meteo\2021\synop.202010.csv
../donnees/meteo\2021\synop.202011.csv
../donnees/meteo\2021\synop.202012.csv
../donnees/meteo\2022\synop.202201.csv
../donnees/meteo\2022\synop.202202.csv
../donnees/meteo\2022\synop.202203.csv
../donnees/meteo\2022\synop.202204.csv
../donnees/meteo\2022\synop.202205.csv
../donnees/meteo\2022\synop.202206.csv
../donnees/meteo\2022\synop.202207.csv
../donnees/meteo\2022\synop.202208.csv
../donnees/meteo\2022\synop.202209.csv
../donnees/meteo\2022\synop.202210.csv
../donnees/meteo\2022\synop.202211.csv
../donnees/meteo\2022\synop.202212.csv
../donnees/meteo\2023\synop.202301.csv
../donnees/meteo\2023\synop.202302.csv
../donnees/meteo\2023\synop.202303.csv
../donnees/meteo\2023\synop.202304.csv
../donnees/meteo\2023\synop.202305.csv
../donnees/meteo\2023\synop.202306.csv
../donnees/meteo\2023\synop.202307.csv
../donnees/meteo\2023\synop.202308.csv
../donnees/meteo\2023\synop.202309.csv
../donnees/meteo\2023\synop.202310.csv
../donnees/meteo\2023\synop.202311.csv